src/Entity/MrBook.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MrBookRepository")
 */
class MrBook extends MrOrm
{
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private $id;
	/**
	 * @ORM\ManyToMany(targetEntity="App\Entity\MrAuthor", inversedBy="books")
	 */
	private $author;

	/**
	 * @ORM\Column(type="string", length=255, nullable=true)
	 */
	private $name;

	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
	private $page_cnt;

	/**
	 * @ORM\Column(type="decimal", precision=10, scale=2)
	 */
	private $price;

	/**
	 * @ORM\Column(type="integer")
	 */
	private $existence;

	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
	private $year;

	/**
	 * @ORM\Column(type="string", length=25, nullable=true)
	 */
	private $isbn;

	/**
	 * @ORM\Column(type="string", length=255, nullable=true)
	 */
	private $url;

	/**
	 * @ORM\Column(type="string", length=10000, nullable=true)
	 */
	private $description;

	public function __construct()
	{
		$this->author = new ArrayCollection();
		$this->mrLeads = new ArrayCollection();
	}

	public function getId(): ?int
	{
		return $this->id;
	}

	/**
	 * @return Collection|MrAuthor[]
	 */
	public function getAuthors(): Collection
	{
		return $this->author;
	}

	public function addAuthor(MrAuthor $author): self
	{
		if (!$this->author->contains($author))
		{
			$this->author[] = $author;
		}

		return $this;
	}

	public function removeAuthor(MrAuthor $author): self
	{
		if ($this->author->contains($author))
		{
			$this->author->removeElement($author);
		}

		return $this;
	}

	public function getName(): ?string
	{
		return $this->name;
	}

	public function setName(?string $name): self
	{
		$this->name = $name;

		return $this;
	}

	public function getPageCnt(): ?int
	{
		return $this->page_cnt;
	}

	public function setPageCnt(?int $page_cnt): self
	{
		$this->page_cnt = $page_cnt;

		return $this;
	}

	public function getPrice(): ?float
	{
		return $this->price;
	}

	public function setPrice(float $price): self
	{
		$this->price = $price;

		return $this;
	}

	const EXISTENCE_NO = 0;
	const EXISTENCE_YES = 1;
	const EXISTENCE_PREORDER = 2;
	const EXISTENCE_WAIT = 3;
	const EXISTENCE_WAIT_5 = 4;

	private static $existences = array(
			self::EXISTENCE_NO       => 'Нет в наличии',
			self::EXISTENCE_YES      => 'Есть',
			self::EXISTENCE_PREORDER => 'Уточняйте',
			self::EXISTENCE_WAIT     => 'Скоро в продаже',
			self::EXISTENCE_WAIT_5   => 'Доставка в течении 5 дней',
	);

	/**
	 * @ORM\ManyToMany(targetEntity=MrLead::class, mappedBy="bookid")
	 */
	private $mrLeads;

	public static function GetExistenceList()
	{
		return self::$existences;
	}

	public function getExistence(): ?int
	{
		return $this->existence;
	}

	public function getExistenceName(): string
	{
		return self::GetExistenceList()[$this->getExistence()];
	}

	public function setExistence(int $existence): self
	{
		$this->existence = $existence;

		return $this;
	}

	public function getYear(): ?int
	{
		return $this->year;
	}

	public function setYear(?int $year): self
	{
		$this->year = $year;

		return $this;
	}

	public function getIsbn(): ?string
	{
		return $this->isbn;
	}

	public function setIsbn(?string $isbn): self
	{
		$this->isbn = $isbn;

		return $this;
	}

	public function getUrl(): ?string
	{
		return $this->url;
	}

	public function setUrl(?string $url): self
	{
		$this->url = $url;

		return $this;
	}

	public function getDescription(): ?string
	{
		return $this->description;
	}

	public function setDescription(?string $description): self
	{
		$this->description = $description;

		return $this;
	}

	/**
	 * @return Collection|MrLead[]
	 */
	public function getMrLeads(): Collection
	{
		return $this->mrLeads;
	}

	public function addMrLead(MrLead $mrLead): self
	{
		if (!$this->mrLeads->contains($mrLead))
		{
			$this->mrLeads[] = $mrLead;
			$mrLead->addBookid($this);
		}

		return $this;
	}

	public function removeMrLead(MrLead $mrLead): self
	{
		if ($this->mrLeads->removeElement($mrLead))
		{
			$mrLead->removeBookid($this);
		}

		return $this;
	}

	public function canDelete(UserInterface $user): bool
	{
		foreach ($user->getRoles() as $role)
		{
			if ($role == 'ROLE_USER')
			{
				return true;
			}
		}

		return false;
	}

	public function isExistence(): bool
	{
		return $this->getExistence() != self::EXISTENCE_NO;
	}
}

src/Form/MrBookType.php
<?php

namespace App\Form;

use App\Entity\MrBook;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MrBookType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder
      ->add('name')
      ->add('page_cnt')
      ->add('price')
      ->add('existence')
      ->add('year')
      ->add('isbn')
      ->add('url')
      ->add('description')// ->add('author')
    ;
  }

  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults([
      'data_class' => MrBook::class,
    ]);
  }
}

src/Controller/MrBookController.php
<?php

namespace App\Controller;

use App\Entity\MrBook;
use App\Form\MrBookType;
use App\Repository\MrBookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MrBookController extends AbstractController
{
  // Standard parameters for get books
  const CNT_ON_PAGE = 10;
  const PAGE = 1; // number of page

  /**
   * @param Request $request
   * @return Response
   */
  public function index(Request $request)
  {
    $repository = $this->getDoctrine()->getRepository(MrBook::class);
    $parameters = $this->getStandardParameters($request->query->getIterator()->getArrayCopy());

    $books = $repository->getByParameters($parameters);

    // TODO: do with cache in future
    $cnt_books = $repository->getBookCount();

    return $this->render('list/index.html.twig', [
      'books'   => $books,
      'cnt'     => count($books),
      'cnt_all' => $cnt_books
    ]);
  }

  /**
   * Check parameters or get base (if not valid)
   *
   * @param array $query_arr
   * @return int[]
   */
  public function getStandardParameters(array $query_arr): array
  {
    return array(
      'on_page' => (int)($query_arr['on_page'] ?? self::CNT_ON_PAGE),
      'page'    => (int)($query_arr['page'] ?? self::PAGE)
    );
  }

  // Constants for search books
  const MAX_LENGTH_SEARCH_TEXT = 100;
  const MAX_RESULT = 10;

  /**
   * Search books by text query. Can use standard parameters (on_page, page)
   *
   * @param Request $request
   * @return Response
   */
  public function searchBooks(Request $request)
  {
    $repository = $this->getDoctrine()->getRepository(MrBook::class);

    $books = array();

    if ($query_text = $request->query->getIterator()->getArrayCopy()['search'] ?? '')
    {
      $parameters = array(
        'query_text' => substr($query_text, 0, self::MAX_LENGTH_SEARCH_TEXT),
        'max_result' => self::MAX_RESULT,
      );

      $books = $repository->searchBooks($parameters);
    }

    return $this->render('list/search.html.twig', [
      'books'        => $books,
      'searched_cnt' => count($books),
    ]);
  }

  public function new(Request $request): Response
  {
    $mrBook = new MrBook();
    $form = $this->createForm(MrBookType::class, $mrBook);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid())
    {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($mrBook);
      $entityManager->flush();

      return $this->redirectToRoute('mr_book_show', ['id'=>$mrBook->getId()]);
    }

    return $this->render('mr_book/new.html.twig', [
      'mr_book' => $mrBook,
      'form'    => $form->createView(),
    ]);
  }

  public function show(MrBook $mrBook): Response
  {
    return $this->render('mr_book/show.html.twig', [
      'mr_book' => $mrBook,
    ]);
  }

  public function edit(Request $request, MrBook $mrBook): Response
  {
    $form = $this->createForm(MrBookType::class, $mrBook);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid())
    {
      $this->getDoctrine()->getManager()->flush();

      return $this->redirectToRoute('mr_book_show', ['id' => $mrBook->getId()]);
    }

    return $this->render('mr_book/edit.html.twig', [
      'mr_book' => $mrBook,
      'form'    => $form->createView(),
    ]);
  }

  public function delete(Request $request, MrBook $mrBook): Response
  {
    if ($this->isCsrfTokenValid('delete' . $mrBook->getId(), $request->request->get('_token')))
    {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->remove($mrBook);

      $entityManager->flush();
    }

    return $this->redirectToRoute('book.list');
  }
}

templates/mr_book/_delete_form.html.twig
<form method="post" action="{{ path('mr_book_delete', {'id': mr_book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mr_book.id) }}">
    <button class="btn btn-danger btn-sm">Удалить книгу</button>
</form>

templates/mr_book/_form.html.twig
<div class="container">
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button class="btn btn-success btn-sm">{{ button_label|default('Save') }}</button>
	{{ form_end(form) }}
</div>

templates/mr_book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование книги{% endblock %}

{% block body %}
	<div class="container">
		<a href="{{ path('book.list') }}" class="btn btn-primary btn-sm">Вернуться в список книг</a>
		<h1>{{ mr_book.getName }}</h1>
		{{ include('mr_book/_form.html.twig', {'button_label': 'Сохранить'}) }}
	</div>
{% endblock %}

templates/mr_book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MrBook index{% endblock %}

{% block body %}
    <h1>MrBook index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Page_cnt</th>
                <th>Price</th>
                <th>Existence</th>
                <th>Year</th>
                <th>Isbn</th>
                <th>Url</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mr_book in mr_books %}
            <tr>
                <td>{{ mr_book.id }}</td>
                <td>{{ mr_book.name }}</td>
                <td>{{ mr_book.pageCnt }}</td>
                <td>{{ mr_book.price }}</td>
                <td>{{ mr_book.existence }}</td>
                <td>{{ mr_book.year }}</td>
                <td>{{ mr_book.isbn }}</td>
                <td>{{ mr_book.url }}</td>
                <td>{{ mr_book.description }}</td>
                <td>
                    <a href="{{ path('mr_book_show', {'id': mr_book.id}) }}">show</a>
                    <a href="{{ path('mr_book_edit', {'id': mr_book.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('mr_book_new') }}">Create new</a>
{% endblock %}

templates/mr_book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новая книга{% endblock %}

{% block body %}
    <div class="container">
        <a href="{{ path('book.list') }}" class="btn btn-primary btn-sm">Вернуться в список книг</a>
        <h1>{{ mr_book.getName }}</h1>
        {{ include('mr_book/_form.html.twig', {'button_label': 'Сохранить'}) }}
    </div>
{% endblock %}

templates/mr_book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ mr_book.name }}{% endblock %}

{% block body %}
	<div class="container">
		<a href="{{ path('book.list') }}" class="btn btn-primary btn-sm"><< назад</a>
		<h1>{{ mr_book.name }}</h1>

		<table class="table table-sm table-hover">
			<tbody>
			<tr>
				<th>Id</th>
				<td>{{ mr_book.id }}</td>
			</tr>
			<tr>
				<th>Количество страниц</th>
				<td>{{ mr_book.pageCnt }}</td>
			</tr>
			<tr>
				<th>Цена</th>
				<td>{{ mr_book.price }}</td>
			</tr>
			<tr>
				<th>Наличие</th>
				<td>{{ mr_book.getExistenceName }}</td>
			</tr>
			<tr>
				<th>Год издания</th>
				<td>{{ mr_book.year }}</td>
			</tr>
			<tr>
				<th>ISBN</th>
				<td>{{ mr_book.isbn }}</td>
			</tr>
			<tr>
				<th>Url</th>
				<td><a href="{{ mr_book.url }}" target="_blank">Ссылка на магазин</a></td>
			</tr>
			<tr>
				<th>Описание книги</th>
				<td>{{ mr_book.description }}</td>
			</tr>
			</tbody>
		</table>

		<div class="row">
			{% if app.user %}
				<div class="d-inline col-md-8">
					<a href="{{ path('mr_book_edit', {'id': mr_book.id}) }}" class="btn btn-primary btn-sm">Редактировать</a>
				</div>
				<div class="d-inline col-md-4">
					{{ include('mr_book/_delete_form.html.twig') }}
				</div>
			{% else %}
				<div class="d-inline col-md-6"><a href="{{ path('mr_book_edit', {'id': mr_book.id}) }}" class="btn btn-primary btn-sm">Редактировать</a></div>
			{% endif %}
		</div>
	</div>
{% endblock %}